_parent_: options/scannerf_blender.yaml

wandb: true
project: scannerf-v1

batch_size: 1                                               # batch size (not used for NeRF/BARF)
max_epoch:                                                  # train to maximum number of epochs (not used for NeRF/BARF)
max_iter: 200000                                            # train to maximum number of iterations


H: 540
W: 960

data:                                                       # data options
    dataset: static_blender                                 # dataset name
    scene: calendar                                         # scene name
    raw_image_size: [2160, 3840]                            # input image sizes [height,width]

arch:
    dim_latent: 256                                         # latent code dimension
    layers_rgb: [null, 128, 3]                              # Last dimension feeds into neural renderer
    posenc:
        L_pose: 4

nerf:
    depth:
        range: [0, 2]

camera:
    focal: 2860.2

scannerf:
    N_obj: 1                                                 # Number of foreground object as a prior