wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/step
      6:
      - 3
    - 1: train/render
      5: 1
      6:
      - 1
    - 1: train/render_fine
      5: 1
      6:
      - 1
    - 1: train/all
      5: 1
      6:
      - 1
    - 1: train/lr
      5: 1
      6:
      - 1
    - 1: train/lr_pose
      5: 1
      6:
      - 1
    python_version: 3.7.11
    start_time: 1645688921
    t:
      1:
      - 1
      4: 3.7.11
      5: 0.12.10
      8:
      - 5
